#1)

If the arrival time is A, the A/60 is Unif(0,1)

So if X, Y are Unif(0,1),

we are asked

$$
  P(|Y-X|<1/4)
$$
this corresponds to the region:

```{r,echo=TRUE}
x<-seq(0,1,0.01)
plot(1, type="n", xlab="", ylab="",xlim=c(0,1),ylim=c(0,1), xaxs = "i",yaxs = "i")
polygon(c(0,0,0.75,1,1,0.25),c(0,0.25,1,1,0.75,0), col='skyblue')

```
so, 1-(3/4)^2=7/16


#2-a) 

1/3

#2-b)

Carl is the first to arrive at 10min mark.

Carl waits more than 10 minutes for anyone to show up if none show up btw 10 and 20 min mark,ie both show up at 20-30, ie. (1/2)^2=1/4

#2-c)

Carl waits more than 10 minutes for both to show up if there is someone arrives btw 20-30, ie. its not the case that both arrive at 10-20, ie. 1-(1/2)^2=3/4

#2-d)

2nd and 3rd arrive at A, B. These are btw 10-30

we are asked P(|A-B|>5)

Let X=A/20, Y=B/20 so that X,Y ~ Unif(0,1)

So P(|A-B|>5)=P(|X-Y|>1/4)

This is the exercise 1 in reverse so 1-7/16=9/16


#5-a)

|Table|X=1|X=2|X=3|X=4|X=5|X=6|Total
|---|---|---|---|---|---|---|---|
|Y=0|$\frac{1}{6}\cdot\frac{1}{2}\binom{1}{0}$|$\frac{1}{6}\cdot\frac{1}{2}^2\binom{2}{0}$|$\frac{1}{6}\cdot\frac{1}{2}^3\binom{3}{0}$|$\frac{1}{6}\cdot\frac{1}{2}^4\binom{4}{0}$|$\frac{1}{6}\cdot\frac{1}{2}^5\binom{5}{0}$|$\frac{1}{6}\cdot\frac{1}{2}^6\binom{6}{0}$|`r sum((1/2)^(1:6))*1/6`
|Y=1|$\frac{1}{6}\cdot\frac{1}{2}\binom{1}{1}$|$\frac{1}{6}\cdot\frac{1}{2}^2\binom{2}{1}$|$\frac{1}{6}\cdot\frac{1}{2}^3\binom{3}{1}$|$\frac{1}{6}\cdot\frac{1}{2}^4\binom{4}{1}$|$\frac{1}{6}\cdot\frac{1}{2}^5\binom{5}{1}$|$\frac{1}{6}\cdot\frac{1}{2}^6\binom{6}{1}$|`r (1/6)*sum(choose(1:6,1)*(1/2)^(1:6))`
|Y=2|0|$\frac{1}{6}\cdot\frac{1}{2}^2\binom{2}{2}$|$\frac{1}{6}\cdot\frac{1}{2}^3\binom{3}{2}$|$\frac{1}{6}\cdot\frac{1}{2}^4\binom{4}{2}$|$\frac{1}{6}\cdot\frac{1}{2}^5\binom{5}{2}$|$\frac{1}{6}\cdot\frac{1}{2}^6\binom{6}{2}$|`r (1/6)*sum(choose(1:6,2)*(1/2)^(1:6))`
|Y=3|0|0|$\frac{1}{6}\cdot\frac{1}{2}^3\binom{3}{3}$|$\frac{1}{6}\cdot\frac{1}{2}^4\binom{4}{3}$|$\frac{1}{6}\cdot\frac{1}{2}^5\binom{5}{3}$|$\frac{1}{6}\cdot\frac{1}{2}^6\binom{6}{3}$|`r (1/6)*sum(choose(1:6,3)*(1/2)^(1:6))`
|Y=4|0|0|0|$\frac{1}{6}\cdot\frac{1}{2}^4\binom{4}{4}$|$\frac{1}{6}\cdot\frac{1}{2}^5\binom{5}{4}$|$\frac{1}{6}\cdot\frac{1}{2}^6\binom{6}{4}$|`r (1/6)*sum(choose(1:6,4)*(1/2)^(1:6))`
|Y=5|0|0|0|0|$\frac{1}{6}\cdot\frac{1}{2}^5\binom{5}{5}$|$\frac{1}{6}\cdot\frac{1}{2}^6\binom{6}{5}$|`r (1/6)*sum(choose(1:6,5)*(1/2)^(1:6))`
|Y=6|0|0|0|0|0|$\frac{1}{6}\cdot\frac{1}{2}^6\binom{6}{6}$|`r (1/6)*sum(choose(1:6,6)*(1/2)^(1:6))`
|TOTAL|`r (1/6)*(1/2)^1*sum(choose(1,0:1))`|`r (1/6)*(1/2)^2*sum(choose(2,0:2))`|`r (1/6)*(1/2)^3*sum(choose(3,0:3))`|`r (1/6)*(1/2)^4*sum(choose(4,0:4))`|`r (1/6)*(1/2)^5*sum(choose(5,0:5))`|`r (1/6)*(1/2)^6*sum(choose(6,0:6))`|`r sum(sapply(0:6,function(x) (1/6)*sum(choose(1:6,x)*(1/2)^(1:6))))`|

No not independent for example 
P(Y=2,X=1)=0 but P(Y=2)P(X=1) is not

#5-b)

Read from the margins

#5-c)

Normalize each row and column by the total at the end of that row, column.


#7)

$$
  f_X(x)=\frac{1}{L}\\
  f_{Y|X}(x,y)=\frac{1}{x}\\
  f_{X,Y}(x,y)=\frac{1}{Lx}\\
  f_X(x)=\int_0^x\frac{1}{Lx}dy=\frac{y}{Lx}\Big|_0^x=\frac{1}{L}\\
  f_{Y|X}=\frac{f_{X,Y}}{f_X}=\frac{1}{Lx}/\frac{1}{L}=\frac{1}{x}\\
  f_Y(y)=\int_y^{L}\frac{1}{Lx}dx=\frac{1}{L}(ln(L)-ln(y))=\frac{1}{L}ln\frac{L}{y}\\
  f_{X|Y}=\frac{f_{Y|X}\cdot f_X}{f_Y}=\frac{\frac{1}{xL}}{\frac{1}{L}ln\frac{L}{y}}=\frac{1}{xln{\frac{L}{y}}}
$$

#8-a)

This is with replacement so,
the probability of Queen happening a times, King b times and Other c times is

$$
(\frac{4}{52})^a(\frac{4}{52})^b(\frac{44}{52})^c
$$
In how many different ways can this happen?

$$
  \binom{5}{a}\binom{5-a}{b}\binom{5-a-b}{c}=\frac{5!}{a!b!c!}
$$

So

$$
  P(X=a,Y=b,Z=c)=\frac{5!}{a!b!c!}(\frac{4}{52})^a(\frac{4}{52})^b(\frac{44}{52})^c
$$

This is the multinomial story.

#8-b)

To marginalize out the Z, notice that a given (X=a, Y=b) happens with only one Z value ie. (5-a-b), there is nothing to sum, or said another way, the sum has only one term.

$$
  P(X=a,Y=b)=P(X=a,Y=b,Z=5-a-b)=\frac{5!}{a!b!c!}(\frac{4}{52})^a(\frac{4}{52})^b(\frac{44}{52})^{5-a-b}
$$

#8-c)

$$
  P(X=a,Y=b,Z=5-a-b)=\frac{\binom{4}{a}\binom{4}{b}\binom{44}{5-a-b}}{\binom{52}{5}}
$$

#9)


#10-a)

$$
  P(X+Y\le t|X=x)=P(Y\le t-x)\\
  =1-e^{-\lambda(t-x)}
$$
and zero for t-x<=0

#10-b)

This is the derivative of part a

$$
  \frac{d}{dt}(1-e^{-\lambda(t-x)})=\frac{d}{dt}(1-e^{-\lambda t}e^{\lambda x})=\lambda e^{\lambda x}e^{-\lambda t}=\lambda e^{\lambda(x-t)}
$$
Is this valid? This is for t>x, its positive and integral wrt t of that from x to +infinity is what? 

$$
  1-e^{-\lambda(t-x)}\Big|_x^{+\infty}=1-(1-1)=1
$$

#10-c) 

$$
  f_{X|T}=\frac{f_{T|X}f_X}{f_T}
$$


$$
  f_{T|X}\cdot f_X=\lambda e^{\lambda(x-t)}\lambda e^{-\lambda x}=\lambda^2e^{-\lambda t}
$$

We know that $f_{X|T}$ should integrate to 1 for x from 0 to t and that the marginal of T is some constant for a given t.

therefore

$$
  \frac{1}{f_T}\int_0^{t} \lambda^2e^{-\lambda t} dx=1\\
  (\frac{\lambda^2}{f_T}e^{-\lambda t})x\Big|_0^t=1\\
  (\frac{\lambda^2}{f_T}e^{-\lambda t})t=1\\
  f_T=\lambda^2te^{-\lambda t}
$$
Hence 
$$
  f_{X|T}=\frac{1}{t}
$$

Is this valid? yes, positive and integrates to 1.

#11-a)

$$
  X\sim N(0,1)\\
  Y|X, Z|X\sim N(x,1)
$$
Joint pdf of X,Y,Z
$$
  \phi(y-x)\phi(z-x)\phi(x)
$$


#11-b) 

Knowing Y gives info about X and hence Z, so not uncond. indep.

#11-c) 

Joint pdf of Y,Z? Integrate out X from the joint of X,Y,Z

$$
  \int_{-\infty}^{+\infty}\phi(y-x)\phi(z-x)\phi(x)dx
$$

https://www.wolframalpha.com/input/?i=integrate+(1%2Fsqrt(2*pi))%5E3e%5E(-(z-x)%5E2%2F2)e%5E(-(y-x)%5E2%2F2)e%5E(-(x)%5E2%2F2)+from+x%3D-infinity+to+x%3D%2Binfinity